# Generated by Django 4.2.3 on 2023-09-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-postdate',)},
        ),
    ]
